// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M5EncoderTestLabelUpdate

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Page1Label;
lv_obj_t * ui_ToggleSwitchStatelabel1;
lv_obj_t * ui_Enc1Arc;
lv_obj_t * ui_Enc1ValueLabel;
lv_obj_t * ui_ArcMinLabel;
lv_obj_t * ui_ArcMaxLabel;
lv_obj_t * ui_Enc1BtnValueLabel;
lv_obj_t * ui_Enc1StaticText1;
lv_obj_t * ui_Enc1StaticText2;
lv_obj_t * ui_Enc2Arc;
lv_obj_t * ui_Enc2ValueLabel;
lv_obj_t * ui_Enc2BtnValueLabel;
lv_obj_t * ui_Enc2StaticText1;
lv_obj_t * ui_Enc2StaticText2;
lv_obj_t * ui_Enc3Arc;
lv_obj_t * ui_Enc3ValueLabel;
lv_obj_t * ui_Enc3BtnValueLabel;
lv_obj_t * ui_Enc3StaticText1;
lv_obj_t * ui_Enc3StaticText2;
lv_obj_t * ui_Enc4Arc;
lv_obj_t * ui_Enc4ValueLabel;
lv_obj_t * ui_Enc4BtnValueLabel;
lv_obj_t * ui_Enc4StaticText1;
lv_obj_t * ui_Enc4StaticText2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Page2label;
lv_obj_t * ui_ToggleSwitchStatelabel2;
lv_obj_t * ui_Enc5Arc;
lv_obj_t * ui_Enc5ValueLabel;
lv_obj_t * ui_ArcMinLabel1;
lv_obj_t * ui_ArcMaxLabel1;
lv_obj_t * ui_Enc5BtnValueLabel;
lv_obj_t * ui_Enc5StaticText1;
lv_obj_t * ui_Enc5StaticText2;
lv_obj_t * ui_Enc6Arc;
lv_obj_t * ui_Enc6ValueLabel;
lv_obj_t * ui_Enc6BtnValueLabel;
lv_obj_t * ui_Enc6StaticText1;
lv_obj_t * ui_Enc6StaticText2;
lv_obj_t * ui_Enc7Arc;
lv_obj_t * ui_Enc7ValueLabel;
lv_obj_t * ui_Enc7BtnValueLabel;
lv_obj_t * ui_Enc7StaticText1;
lv_obj_t * ui_Enc7StaticText2;
lv_obj_t * ui_Enc8Arc;
lv_obj_t * ui_Enc8ValueLabel;
lv_obj_t * ui_Enc8BtnValueLabel;
lv_obj_t * ui_Enc8StaticText1;
lv_obj_t * ui_Enc8StaticText2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
