// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M5EncoderTestLabelUpdate

#ifndef _M5ENCODERTESTLABELUPDATE_UI_H
#define _M5ENCODERTESTLABELUPDATE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Page1Label;
extern lv_obj_t * ui_ToggleSwitchStatelabel1;
extern lv_obj_t * ui_Enc1Arc;
extern lv_obj_t * ui_Enc1ValueLabel;
extern lv_obj_t * ui_ArcMinLabel;
extern lv_obj_t * ui_ArcMaxLabel;
extern lv_obj_t * ui_Enc1BtnValueLabel;
extern lv_obj_t * ui_Enc1StaticText1;
extern lv_obj_t * ui_Enc1StaticText2;
extern lv_obj_t * ui_Enc2Arc;
extern lv_obj_t * ui_Enc2ValueLabel;
extern lv_obj_t * ui_Enc2BtnValueLabel;
extern lv_obj_t * ui_Enc2StaticText1;
extern lv_obj_t * ui_Enc2StaticText2;
extern lv_obj_t * ui_Enc3Arc;
extern lv_obj_t * ui_Enc3ValueLabel;
extern lv_obj_t * ui_Enc3BtnValueLabel;
extern lv_obj_t * ui_Enc3StaticText1;
extern lv_obj_t * ui_Enc3StaticText2;
extern lv_obj_t * ui_Enc4Arc;
extern lv_obj_t * ui_Enc4ValueLabel;
extern lv_obj_t * ui_Enc4BtnValueLabel;
extern lv_obj_t * ui_Enc4StaticText1;
extern lv_obj_t * ui_Enc4StaticText2;
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Page2label;
extern lv_obj_t * ui_ToggleSwitchStatelabel2;
extern lv_obj_t * ui_Enc5Arc;
extern lv_obj_t * ui_Enc5ValueLabel;
extern lv_obj_t * ui_ArcMinLabel1;
extern lv_obj_t * ui_ArcMaxLabel1;
extern lv_obj_t * ui_Enc5BtnValueLabel;
extern lv_obj_t * ui_Enc5StaticText1;
extern lv_obj_t * ui_Enc5StaticText2;
extern lv_obj_t * ui_Enc6Arc;
extern lv_obj_t * ui_Enc6ValueLabel;
extern lv_obj_t * ui_Enc6BtnValueLabel;
extern lv_obj_t * ui_Enc6StaticText1;
extern lv_obj_t * ui_Enc6StaticText2;
extern lv_obj_t * ui_Enc7Arc;
extern lv_obj_t * ui_Enc7ValueLabel;
extern lv_obj_t * ui_Enc7BtnValueLabel;
extern lv_obj_t * ui_Enc7StaticText1;
extern lv_obj_t * ui_Enc7StaticText2;
extern lv_obj_t * ui_Enc8Arc;
extern lv_obj_t * ui_Enc8ValueLabel;
extern lv_obj_t * ui_Enc8BtnValueLabel;
extern lv_obj_t * ui_Enc8StaticText1;
extern lv_obj_t * ui_Enc8StaticText2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
