// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: test1

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page2label = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Page2label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page2label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Page2label, 0);
    lv_obj_set_y(ui_Page2label, 105);
    lv_obj_set_align(ui_Page2label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page2label, "P2");

    ui_ToggleSwitchStatelabel2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ToggleSwitchStatelabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToggleSwitchStatelabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ToggleSwitchStatelabel2, 89);
    lv_obj_set_y(ui_ToggleSwitchStatelabel2, 16);
    lv_obj_set_align(ui_ToggleSwitchStatelabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToggleSwitchStatelabel2, "TSV");
    lv_obj_set_style_text_color(ui_ToggleSwitchStatelabel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToggleSwitchStatelabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ToggleSwitchStatelabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc5Arc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Enc5Arc, 125);
    lv_obj_set_height(ui_Enc5Arc, 125);
    lv_obj_set_x(ui_Enc5Arc, 0);
    lv_obj_set_y(ui_Enc5Arc, 50);
    lv_obj_set_align(ui_Enc5Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc5Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc5Arc, lv_color_hex(0xFFBF03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc5Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc5Arc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc5Arc, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc5Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc5Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc5Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc5Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc5Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc5Arc, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc5Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc5Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc5Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc5Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc5Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc5Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc5ValueLabel = lv_label_create(ui_Enc5Arc);
    lv_obj_set_width(ui_Enc5ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc5ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc5ValueLabel, 0);
    lv_obj_set_y(ui_Enc5ValueLabel, -10);
    lv_obj_set_align(ui_Enc5ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc5ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc5ValueLabel, lv_color_hex(0xFFBE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc5ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc5ValueLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMinLabel1 = lv_label_create(ui_Enc5Arc);
    lv_obj_set_width(ui_ArcMinLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcMinLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcMinLabel1, -40);
    lv_obj_set_y(ui_ArcMinLabel1, 55);
    lv_obj_set_align(ui_ArcMinLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcMinLabel1, "0");
    lv_obj_set_style_text_color(ui_ArcMinLabel1, lv_color_hex(0xFFBE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcMinLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMaxLabel1 = lv_label_create(ui_Enc5Arc);
    lv_obj_set_width(ui_ArcMaxLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcMaxLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcMaxLabel1, 40);
    lv_obj_set_y(ui_ArcMaxLabel1, 55);
    lv_obj_set_align(ui_ArcMaxLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcMaxLabel1, "100");
    lv_obj_set_style_text_color(ui_ArcMaxLabel1, lv_color_hex(0xFFBE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcMaxLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc5BtnValueLabel = lv_label_create(ui_Enc5Arc);
    lv_obj_set_width(ui_Enc5BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc5BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc5BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc5BtnValueLabel, 35);
    lv_obj_set_align(ui_Enc5BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc5BtnValueLabel, "BV");

    ui_Enc5StaticText1 = lv_label_create(ui_Enc5Arc);
    lv_obj_set_width(ui_Enc5StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc5StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc5StaticText1, 0);
    lv_obj_set_y(ui_Enc5StaticText1, 18);
    lv_obj_set_align(ui_Enc5StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc5StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc5StaticText1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc5StaticText2 = lv_label_create(ui_Enc5Arc);
    lv_obj_set_width(ui_Enc5StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc5StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc5StaticText2, 0);
    lv_obj_set_y(ui_Enc5StaticText2, -35);
    lv_obj_set_align(ui_Enc5StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc5StaticText2, "Ch5");
    lv_obj_set_style_text_font(ui_Enc5StaticText2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc6Arc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Enc6Arc, lv_pct(30));
    lv_obj_set_height(ui_Enc6Arc, lv_pct(30));
    lv_obj_set_x(ui_Enc6Arc, -65);
    lv_obj_set_y(ui_Enc6Arc, -40);
    lv_obj_set_align(ui_Enc6Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc6Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc6Arc, lv_color_hex(0x00EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc6Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc6Arc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc6Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc6Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc6Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc6Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc6Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc6Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc6Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc6Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc6Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc6Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc6Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc6Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc6Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc6ValueLabel = lv_label_create(ui_Enc6Arc);
    lv_obj_set_width(ui_Enc6ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc6ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Enc6ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc6ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc6ValueLabel, lv_color_hex(0x00EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc6ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc6ValueLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc6BtnValueLabel = lv_label_create(ui_Enc6Arc);
    lv_obj_set_width(ui_Enc6BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc6BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc6BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc6BtnValueLabel, 31);
    lv_obj_set_align(ui_Enc6BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc6BtnValueLabel, "BV");

    ui_Enc6StaticText1 = lv_label_create(ui_Enc6Arc);
    lv_obj_set_width(ui_Enc6StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc6StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc6StaticText1, 0);
    lv_obj_set_y(ui_Enc6StaticText1, 18);
    lv_obj_set_align(ui_Enc6StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc6StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc6StaticText1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc6StaticText2 = lv_label_create(ui_Enc6Arc);
    lv_obj_set_width(ui_Enc6StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc6StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc6StaticText2, 0);
    lv_obj_set_y(ui_Enc6StaticText2, -18);
    lv_obj_set_align(ui_Enc6StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc6StaticText2, "Ch6");
    lv_obj_set_style_text_font(ui_Enc6StaticText2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc7Arc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Enc7Arc, lv_pct(30));
    lv_obj_set_height(ui_Enc7Arc, lv_pct(30));
    lv_obj_set_x(ui_Enc7Arc, 65);
    lv_obj_set_y(ui_Enc7Arc, -40);
    lv_obj_set_align(ui_Enc7Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc7Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc7Arc, lv_color_hex(0x03EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc7Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc7Arc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc7Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc7Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc7Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc7Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc7Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc7Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc7Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc7Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc7Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc7Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc7Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc7Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc7Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc7ValueLabel = lv_label_create(ui_Enc7Arc);
    lv_obj_set_width(ui_Enc7ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc7ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Enc7ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc7ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc7ValueLabel, lv_color_hex(0x00EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc7ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc7ValueLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc7BtnValueLabel = lv_label_create(ui_Enc7Arc);
    lv_obj_set_width(ui_Enc7BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc7BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc7BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc7BtnValueLabel, 31);
    lv_obj_set_align(ui_Enc7BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc7BtnValueLabel, "BV");

    ui_Enc7StaticText1 = lv_label_create(ui_Enc7Arc);
    lv_obj_set_width(ui_Enc7StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc7StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc7StaticText1, 0);
    lv_obj_set_y(ui_Enc7StaticText1, 18);
    lv_obj_set_align(ui_Enc7StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc7StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc7StaticText1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc7StaticText2 = lv_label_create(ui_Enc7Arc);
    lv_obj_set_width(ui_Enc7StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc7StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc7StaticText2, 0);
    lv_obj_set_y(ui_Enc7StaticText2, -18);
    lv_obj_set_align(ui_Enc7StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc7StaticText2, "Ch7");
    lv_obj_set_style_text_font(ui_Enc7StaticText2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc8Arc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Enc8Arc, lv_pct(30));
    lv_obj_set_height(ui_Enc8Arc, lv_pct(30));
    lv_obj_set_x(ui_Enc8Arc, 0);
    lv_obj_set_y(ui_Enc8Arc, -80);
    lv_obj_set_align(ui_Enc8Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc8Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc8Arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc8Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc8Arc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc8Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc8Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc8Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc8Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc8Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc8Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc8Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc8Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc8Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc8Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc8Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc8Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc8Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc8ValueLabel = lv_label_create(ui_Enc8Arc);
    lv_obj_set_width(ui_Enc8ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc8ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Enc8ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc8ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc8ValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc8ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc8ValueLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc8BtnValueLabel = lv_label_create(ui_Enc8Arc);
    lv_obj_set_width(ui_Enc8BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc8BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc8BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc8BtnValueLabel, 31);
    lv_obj_set_align(ui_Enc8BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc8BtnValueLabel, "BV");

    ui_Enc8StaticText1 = lv_label_create(ui_Enc8Arc);
    lv_obj_set_width(ui_Enc8StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc8StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc8StaticText1, 0);
    lv_obj_set_y(ui_Enc8StaticText1, 18);
    lv_obj_set_align(ui_Enc8StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc8StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc8StaticText1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc8StaticText2 = lv_label_create(ui_Enc8Arc);
    lv_obj_set_width(ui_Enc8StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc8StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc8StaticText2, 0);
    lv_obj_set_y(ui_Enc8StaticText2, -18);
    lv_obj_set_align(ui_Enc8StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc8StaticText2, "Ch8");
    lv_obj_set_style_text_font(ui_Enc8StaticText2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
