// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: test1

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Page1Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Page1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Page1Label, 0);
    lv_obj_set_y(ui_Page1Label, 105);
    lv_obj_set_align(ui_Page1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page1Label, "P1");

    ui_ToggleSwitchStatelabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ToggleSwitchStatelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToggleSwitchStatelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ToggleSwitchStatelabel1, 89);
    lv_obj_set_y(ui_ToggleSwitchStatelabel1, 16);
    lv_obj_set_align(ui_ToggleSwitchStatelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToggleSwitchStatelabel1, "TSV");
    lv_obj_set_style_text_color(ui_ToggleSwitchStatelabel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToggleSwitchStatelabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ToggleSwitchStatelabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc1Arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Enc1Arc, 125);
    lv_obj_set_height(ui_Enc1Arc, 125);
    lv_obj_set_x(ui_Enc1Arc, 0);
    lv_obj_set_y(ui_Enc1Arc, 50);
    lv_obj_set_align(ui_Enc1Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc1Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc1Arc, lv_color_hex(0xFFBF03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc1Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc1Arc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc1Arc, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc1Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc1Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc1Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc1Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc1Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc1Arc, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc1Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc1Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc1Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc1Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc1Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc1Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc1ValueLabel = lv_label_create(ui_Enc1Arc);
    lv_obj_set_width(ui_Enc1ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc1ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc1ValueLabel, 0);
    lv_obj_set_y(ui_Enc1ValueLabel, -10);
    lv_obj_set_align(ui_Enc1ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc1ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc1ValueLabel, lv_color_hex(0xFFBE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc1ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc1ValueLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMinLabel = lv_label_create(ui_Enc1Arc);
    lv_obj_set_width(ui_ArcMinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcMinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcMinLabel, -40);
    lv_obj_set_y(ui_ArcMinLabel, 55);
    lv_obj_set_align(ui_ArcMinLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcMinLabel, "0");
    lv_obj_set_style_text_color(ui_ArcMinLabel, lv_color_hex(0xFFBE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcMinLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMaxLabel = lv_label_create(ui_Enc1Arc);
    lv_obj_set_width(ui_ArcMaxLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcMaxLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcMaxLabel, 40);
    lv_obj_set_y(ui_ArcMaxLabel, 55);
    lv_obj_set_align(ui_ArcMaxLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcMaxLabel, "100");
    lv_obj_set_style_text_color(ui_ArcMaxLabel, lv_color_hex(0xFFBE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcMaxLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc1BtnValueLabel = lv_label_create(ui_Enc1Arc);
    lv_obj_set_width(ui_Enc1BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc1BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc1BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc1BtnValueLabel, 35);
    lv_obj_set_align(ui_Enc1BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc1BtnValueLabel, "BV");

    ui_Enc1StaticText1 = lv_label_create(ui_Enc1Arc);
    lv_obj_set_width(ui_Enc1StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc1StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc1StaticText1, 0);
    lv_obj_set_y(ui_Enc1StaticText1, 18);
    lv_obj_set_align(ui_Enc1StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc1StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc1StaticText1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc1StaticText2 = lv_label_create(ui_Enc1Arc);
    lv_obj_set_width(ui_Enc1StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc1StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc1StaticText2, 0);
    lv_obj_set_y(ui_Enc1StaticText2, -35);
    lv_obj_set_align(ui_Enc1StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc1StaticText2, "Ch1");
    lv_obj_set_style_text_font(ui_Enc1StaticText2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc2Arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Enc2Arc, lv_pct(30));
    lv_obj_set_height(ui_Enc2Arc, lv_pct(30));
    lv_obj_set_x(ui_Enc2Arc, -65);
    lv_obj_set_y(ui_Enc2Arc, -40);
    lv_obj_set_align(ui_Enc2Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc2Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc2Arc, lv_color_hex(0x00EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc2Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc2Arc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc2Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc2Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc2Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc2Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc2Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc2Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc2Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc2Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc2Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc2Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc2ValueLabel = lv_label_create(ui_Enc2Arc);
    lv_obj_set_width(ui_Enc2ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc2ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Enc2ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc2ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc2ValueLabel, lv_color_hex(0x00EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc2ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc2ValueLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc2BtnValueLabel = lv_label_create(ui_Enc2Arc);
    lv_obj_set_width(ui_Enc2BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc2BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc2BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc2BtnValueLabel, 30);
    lv_obj_set_align(ui_Enc2BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc2BtnValueLabel, "BV");

    ui_Enc2StaticText1 = lv_label_create(ui_Enc2Arc);
    lv_obj_set_width(ui_Enc2StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc2StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc2StaticText1, 0);
    lv_obj_set_y(ui_Enc2StaticText1, 18);
    lv_obj_set_align(ui_Enc2StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc2StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc2StaticText1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc2StaticText2 = lv_label_create(ui_Enc2Arc);
    lv_obj_set_width(ui_Enc2StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc2StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc2StaticText2, 0);
    lv_obj_set_y(ui_Enc2StaticText2, -18);
    lv_obj_set_align(ui_Enc2StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc2StaticText2, "Ch2");
    lv_obj_set_style_text_font(ui_Enc2StaticText2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc3Arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Enc3Arc, lv_pct(30));
    lv_obj_set_height(ui_Enc3Arc, lv_pct(30));
    lv_obj_set_x(ui_Enc3Arc, 65);
    lv_obj_set_y(ui_Enc3Arc, -40);
    lv_obj_set_align(ui_Enc3Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc3Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc3Arc, lv_color_hex(0x03EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc3Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc3Arc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc3Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc3Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc3Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc3Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc3Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc3Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc3Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc3Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc3Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc3Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc3Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc3Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc3Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc3ValueLabel = lv_label_create(ui_Enc3Arc);
    lv_obj_set_width(ui_Enc3ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc3ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Enc3ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc3ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc3ValueLabel, lv_color_hex(0x00EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc3ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc3ValueLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc3BtnValueLabel = lv_label_create(ui_Enc3Arc);
    lv_obj_set_width(ui_Enc3BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc3BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc3BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc3BtnValueLabel, 31);
    lv_obj_set_align(ui_Enc3BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc3BtnValueLabel, "BV");

    ui_Enc3StaticText1 = lv_label_create(ui_Enc3Arc);
    lv_obj_set_width(ui_Enc3StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc3StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc3StaticText1, 0);
    lv_obj_set_y(ui_Enc3StaticText1, 18);
    lv_obj_set_align(ui_Enc3StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc3StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc3StaticText1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc3StaticText2 = lv_label_create(ui_Enc3Arc);
    lv_obj_set_width(ui_Enc3StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc3StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc3StaticText2, 0);
    lv_obj_set_y(ui_Enc3StaticText2, -18);
    lv_obj_set_align(ui_Enc3StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc3StaticText2, "Ch3");
    lv_obj_set_style_text_font(ui_Enc3StaticText2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc4Arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Enc4Arc, lv_pct(30));
    lv_obj_set_height(ui_Enc4Arc, lv_pct(30));
    lv_obj_set_x(ui_Enc4Arc, 0);
    lv_obj_set_y(ui_Enc4Arc, -80);
    lv_obj_set_align(ui_Enc4Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Enc4Arc, 50);
    lv_obj_set_style_arc_color(ui_Enc4Arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc4Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc4Arc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Enc4Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Enc4Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Enc4Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Enc4Arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Enc4Arc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Enc4Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Enc4Arc, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Enc4Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Enc4Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Enc4Arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Enc4Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Enc4Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Enc4Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Enc4ValueLabel = lv_label_create(ui_Enc4Arc);
    lv_obj_set_width(ui_Enc4ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc4ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Enc4ValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc4ValueLabel, "AV");
    lv_obj_set_style_text_color(ui_Enc4ValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Enc4ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Enc4ValueLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc4BtnValueLabel = lv_label_create(ui_Enc4Arc);
    lv_obj_set_width(ui_Enc4BtnValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc4BtnValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc4BtnValueLabel, 0);
    lv_obj_set_y(ui_Enc4BtnValueLabel, 31);
    lv_obj_set_align(ui_Enc4BtnValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc4BtnValueLabel, "BV");

    ui_Enc4StaticText1 = lv_label_create(ui_Enc4Arc);
    lv_obj_set_width(ui_Enc4StaticText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc4StaticText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc4StaticText1, 0);
    lv_obj_set_y(ui_Enc4StaticText1, 18);
    lv_obj_set_align(ui_Enc4StaticText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc4StaticText1, "SET");
    lv_obj_set_style_text_font(ui_Enc4StaticText1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enc4StaticText2 = lv_label_create(ui_Enc4Arc);
    lv_obj_set_width(ui_Enc4StaticText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Enc4StaticText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Enc4StaticText2, 0);
    lv_obj_set_y(ui_Enc4StaticText2, -18);
    lv_obj_set_align(ui_Enc4StaticText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Enc4StaticText2, "Ch4");
    lv_obj_set_style_text_font(ui_Enc4StaticText2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 34);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_x(ui_Switch1, 87);
    lv_obj_set_y(ui_Switch1, 40);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_WiFi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFi, -87);
    lv_obj_set_y(ui_WiFi, 16);
    lv_obj_set_align(ui_WiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFi, "WIFI");

    ui_MQTT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MQTT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MQTT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MQTT, -87);
    lv_obj_set_y(ui_MQTT, 36);
    lv_obj_set_align(ui_MQTT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTT, "MQTT");

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
